version: '3.8'

services:
  api-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: belanjayuk_api_dev
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./appsettings.json:/app/appsettings.json:ro
    restart: unless-stopped
