version: '3.8'

services:
  api-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: belanjayuk_api_prod
    ports:
      - "5003:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ./appsettings.json:/app/appsettings.json:ro
      - ./wwwroot/uploads:/app/wwwroot/uploads
    restart: unless-stopped
    networks:
      - default
      - sql_belanjayuk_default

networks:
  sql_belanjayuk_default:
    external: true
