version: '3.8'

services:
  api-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: belanjayuk_api_prod
    ports:
      - "5003:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ./appsettings.json:/app/appsettings.json:ro
    restart: unless-stopped
